import { useEffect, useState } from "react"
import { useOutletContext } from "react-router-dom"

function ResidentDashboardPage() {
    const {developmentBackendLink, productionBackendLink, setSuccessAlert, navigate} = useOutletContext();

    const user = JSON.parse(sessionStorage.getItem("resident"))

    const [wasteData, setWasteData] = useState([]);

    let currentDate = new Date();
    let currentMonthName = currentDate.toLocaleString('default', {month: 'long' });

    const logWasteSubmit = (event) => {
        event.preventDefault()


    }

    useEffect(() => {
        if (!user) {
            navigate("/")
            return
        }
        const requestOptions = {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({id: user.id}),
        }

        fetch(`${developmentBackendLink}/resident-dashboard`, requestOptions)
            .then((response) => response.json())
            .then((data) => {
                console.log(data)
                setWasteData(data.waste_per_month)
            })
    }, [wasteData, user])

    return (
        <div>
            <h1>Resident Dashboard</h1>
            <hr />

            <div className="row">
                <div className="col-lg-7 col-md-7 col-sm-12-col xs-12" style={{"borderRight": "1px solid #fff"}}>
                    <h3>Waste Generated by Month</h3>
                    <table className="table table-dark table-hover table-striped">
                        <thead>
                            <tr>
                                <td>Month</td>
                                <td>Total Waste Generated (kg)</td>
                            </tr>
                        </thead>
                        <tbody>
                            {wasteData.map((w, index) => (
                                <tr key={index}>
                                    <td>{w.month}</td>
                                    <td>{w.waste_amount} kg</td>  
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                <div className="col-lg-5 col-md-5 col-sm-12- col-xs-12">
                    <h3>Log Waste Generated</h3>

                    <form onSubmit={logWasteSubmit} method="post">
                        <input type="number" name="waste_amount" id="waste_amount" placeholder="Amount of Waste(kg)" className="form-control" />
                        <select class="form-select" aria-label="Default select example" style={{"marginTop": "1%"}}>
                            <option selected value={currentMonthName}>{currentMonthName}</option>
                            <option value="January">January</option>
                            <option value="February">February</option>
                            <option value="March">March</option>
                            <option value="April">April</option>
                            <option value="May">May</option>
                            <option value="June">June</option>
                            <option value="July">July</option>
                            <option value="August">August</option>
                            <option value="September">September</option>
                            <option value="October">October</option>
                            <option value="November">November</option>
                            <option value="December">December</option>
                        </select>
                    </form>
                </div>
            </div>
        </div>
    )
}

export default ResidentDashboardPage